import axios from 'axios';

export const GETTING_PRODUCE_START = 'GETTING_PRODUCE_START';
export const GETTING_PRODUCE_SUCCESS = 'GETTING_PRODUCE_SUCCESS';
export const GETTING_PRODUCE_ERROR = 'GETTING_PRODUCE_ERROR';

export const ADDING_PRODUCE_START = 'ADDING_PRODUCE_START';
export const ADDING_PRODUCE_SUCCESS = 'ADDING_PRODUCE_SUCCESS';
export const ADDING_PRODUCE_ERROR = 'ADDING_PRODUCE_ERROR';


export const EDITING_PRODUCE_START = 'EDITING_PRODUCE_START';
export const EDITING_PRODUCE_SUCCESS = 'EDITING_PRODUCE_SUCCESS';
export const EDITING_PRODUCE_ERROR = 'EDITING_PRODUCE_ERROR';

export const DELETING_PRODUCE_START = 'DELETING_PRODUCE_START';
export const DELETING_PRODUCE_SUCCESS = 'DELETING_PRODUCE_SUCCESS';
export const DELETING_PRODUCE_ERROR = 'DELETING_PRODUCE_ERROR';


export function getFarmerProduce() {
   return (dispatch) => {
       dispatch({type:GETTING_PRODUCE_START});
      
   }
}